image: openjdk:11

variables:
  VERSION: 0.0.1-SNAPSHOT

stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew
  
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    
build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
  only:
    - main
    
test:
  stage: test
  script:
    - ./gradlew check
  artifacts:
    reports:
      junit: build/reports/tests/**/index.html
    
pages:
  stage: deploy
  script:
    - java -jar build/libs/trade-system-$VERSION.jar &
    - mkdir public
    - echo "var spec = " > public/api-docs.js
    - curl -L http://localhost:8080/api-docs >> public/api-docs.js
    - cp -rp docs/* public
  artifacts:
    paths:
      - public
  only:
    - main
