image: openjdk:11

variables:
  VERSION: 0.0.1-SNAPSHOT

stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew
  
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    
build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
  only:
    - main
    
test:
  stage: test
  script:
    - ./gradlew check
  artifacts:
    reports:
      junit: build/reports/tests/**/index.html
    
pages:
  stage: deploy
  script:
    - echo "Hello World!" > public/index.html
  artifacts:
    paths:
      - docs
  only:
    - main
